import { OnModuleDestroy, OnModuleInit } from "@nestjs/common";
import { DataSource, Repository } from "typeorm";
import { TaxEvent } from "../tax/entities/tax-event.entity";
import { ShopEvent } from "./entities/shop-event.entity";
import { TokenShopSyncState } from "./entities/tokenshop-sync-state.entity";
export declare class TokenShopListenerService implements OnModuleInit, OnModuleDestroy {
    private readonly dataSource;
    private readonly taxEventRepo;
    private readonly shopEventRepo;
    private readonly syncStateRepo;
    private static readonly SYNC_STATE_ID;
    private readonly logger;
    private readonly pollIntervalMs;
    private readonly rpcUrl;
    private readonly tokenShopAddress;
    private readonly provider;
    private readonly contract;
    private readonly interface;
    private readonly ethAddress;
    private readonly ethUsdSnapshot;
    private readonly ethUsdSnapshotAt;
    private timer;
    private syncInProgress;
    private usingWebSocket;
    private wsProvider;
    private wsContract;
    private readonly wsRpcUrl;
    private triTokenAddress;
    constructor(dataSource: DataSource, taxEventRepo: Repository<TaxEvent>, shopEventRepo: Repository<ShopEvent>, syncStateRepo: Repository<TokenShopSyncState>);
    onModuleInit(): Promise<void>;
    onModuleDestroy(): void;
    private startWebSocket;
    private handleWebSocketEvent;
    private schedule;
    syncNow(): Promise<{
        status: string;
        lastSyncedBlock: number;
    }>;
    private syncOnce;
    private getOrCreateSyncState;
    private parseLog;
    private persistParsedEvent;
    private normalizePaymentAmount;
    private estimateUnitPriceUsd;
    private parsePositiveNumber;
    private formatError;
}
